services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\ContactBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaContactBundle.php'
